version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./db:/app/db
    networks:
      - abrahamic-network

networks:
  abrahamic-network:
    driver: bridge
