name: Docker Build & Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/abrahamic-scriptures:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/abrahamic-scriptures:${{ github.sha }} \
            .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/abrahamic-scriptures:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/abrahamic-scriptures:${{ github.sha }}